### ISSUE TITLE
Command to generate the files by label-folder

### ISSUE THREAD

**Issue by kayzzen01** [416365416c/rust-filer#1]
Hi,

I tried using rust-filer, but without success. I don't know if the program is ready yet, my knowledge of rust is pretty bad =(

Before using it I checked that it correctly listed the labels and correctly showed most of the labels.

`./rust_filer -l takeout-gmail.mbox`

So I ran the command below, it was processing for a while, but it didn't generate the files.

`./rust_filer takeout-gmail.mbox`

Can you tell me if I did something wrong?

**Comment by 416365416c** [comment]
I wouldn't say the program is ready yet, unfortunately I had to put this project aside and haven't had a chance to get back to it and complete it. However you are invoking it correctly, and it should generate some files (in the current directory).

I just tried it again and it is working for me when invoked like that. Even though it takes a long time to run, it should start generating files immediately.

Note that the default labels saved are "Drafts,Sent,Inbox,Archived" and the default labels blocked are "Spam,Deleted". Some of the "ready" work that is missing is to explain this properly, and to finish implementing changing these values with the command line flags. But if your labels, as listed with -l, do not include "Drafts", "Sent", "Inbox", or "Archived" (perhaps due to localization) then that is one reason it might not generate files. Should probably print a warning in that case...

**Comment by kayzzen01** [comment]
I believe you are correct. Due to my localization the files are not generated, the names are different from the default(English). Luckily I managed to solve my problem in another way.

At the moment I'm also focused on other projects, but I want to learn Rust. I thought your project was really cool, especially for those who want to study and increase their knowledge of the language. In the future I should use your project as a form of study =)

Thank you for your attention.
